# Generated by Django 4.0.1 on 2022-01-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together={('played_at', 'ms_played', 'from_import', 'track')},
        ),
    ]
