# Generated by Django 4.0.1 on 2022-01-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulkHistory',
            new_name='SteamingHistory',
        ),
    ]
