# Generated by Django 4.0.1 on 2022-01-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='album_art_300',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='album_art_64',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='albums',
            name='album_art_640',
            field=models.URLField(null=True),
        ),
    ]
