# Generated by Django 4.0.1 on 2022-01-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_albums_album_art_300_albums_album_art_64_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='album_art_300',
            new_name='album_cover_300',
        ),
        migrations.RenameField(
            model_name='albums',
            old_name='album_art_64',
            new_name='album_cover_64',
        ),
        migrations.RenameField(
            model_name='albums',
            old_name='album_art_640',
            new_name='album_cover_640',
        ),
    ]
