# Generated by Django 4.0.1 on 2022-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_spotifyauthorizationtokens_scope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyAuthorizationTokens',
        ),
    ]
